AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  shop

  Sample SAM Template for shop

Globals:
  Function:
    Timeout: 20

Resources:
  CreateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: DynamoDBApp/
      Handler: handler.CreateUserFunction::handleRequest
      Runtime: java11
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserTable
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:DescribeTable
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
                - dynamodb:Query
                - dynamodb:Scan
              Resource: !GetAtt UserTable.Arn
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          PARAM1: VALUE
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
      Events:
        HttpRequest:
          Type: Api
          Properties:
            Path: /users
            Method: POST

  GetUserListFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: DynamoDBApp/
      Handler: handler.GetUserListFunction::handleRequest
      Runtime: java11
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserTable
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:DescribeTable
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
                - dynamodb:Query
                - dynamodb:Scan
              Resource: !GetAtt UserTable.Arn
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:DescribeTable
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
                - dynamodb:Query
                - dynamodb:Scan
              Resource: !GetAtt UserTable.Arn
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:DescribeTable
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
                - dynamodb:Query
                - dynamodb:Scan
              Resource: !GetAtt UserTable.Arn
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:DescribeTable
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
                - dynamodb:Query
                - dynamodb:Scan
              Resource: !GetAtt UserTable.Arn
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:DescribeTable
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
                - dynamodb:Query
                - dynamodb:Scan
              Resource: !GetAtt UserTable.Arn
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          PARAM1: VALUE
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
      Events:
        HttpRequest:
          Type: Api
          Properties:
            Path: /users
            Method: GET

  UpdateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: DynamoDBApp/
      Handler: handler.UpdateUserFunction::handleRequest
      Runtime: java11
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:DescribeTable
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
                - dynamodb:Query
                - dynamodb:Scan
              Resource: !GetAtt UserTable.Arn
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          PARAM1: VALUE
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
      Events:
        HttpRequest:
          Type: Api
          Properties:
            Path: /users/{email}
            Method: PUT

  DeleteUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: DynamoDBApp/
      Handler: handler.DeleteUserFunction::handleRequest
      Runtime: java11
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:DescribeTable
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
                - dynamodb:Query
                - dynamodb:Scan
              Resource: !GetAtt UserTable.Arn
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          PARAM1: VALUE
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
      Events:
        HttpRequest:
          Type: Api
          Properties:
            Path: /users/{email}
            Method: DELETE

  GetUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: DynamoDBApp/
      Handler: handler.GetUserFunction::handleRequest
      Runtime: java11
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
              Resource: !GetAtt UserTable.Arn
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          PARAM1: VALUE
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
      Events:
        HttpRequest:
          Type: Api
          Properties:
            Path: /users/{email}
            Method: GET

  GetUserListByQueryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: DynamoDBApp/
      Handler: handler.GetUserListByQueryFunction::handleRequest
      Runtime: java11
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:DescribeTable
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
                - dynamodb:Query
                - dynamodb:Scan
              Resource: !GetAtt UserTable.Arn
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:DescribeTable
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
                - dynamodb:Query
                - dynamodb:Scan
              Resource: !GetAtt UserTable.Arn
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:DescribeTable
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
                - dynamodb:Query
                - dynamodb:Scan
              Resource: !GetAtt UserTable.Arn
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:DescribeTable
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
                - dynamodb:Query
                - dynamodb:Scan
              Resource: !GetAtt UserTable.Arn
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:DescribeTable
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
                - dynamodb:Query
                - dynamodb:Scan
              Resource: !GetAtt UserTable.Arn
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          PARAM1: VALUE
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
      Events:
        HttpRequest:
          Type: Api
          Properties:
            Path: /match
            Method: POST

  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: user-db
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
        - AttributeName: name
          AttributeType: S
        - AttributeName: location
          AttributeType: S
        - AttributeName: birthday
          AttributeType: N
        - AttributeName: registration
          AttributeType: N
        - AttributeName: country
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: country-name-index
          Projection:
            ProjectionType: ALL
          KeySchema:
            - AttributeName: country
              KeyType: HASH
            - AttributeName: name
              KeyType: RANGE
        - IndexName: country-birthday-index
          Projection:
            ProjectionType: ALL
          KeySchema:
            - AttributeName: country
              KeyType: HASH
            - AttributeName: birthday
              KeyType: RANGE
        - IndexName: country-location-index
          Projection:
            ProjectionType: ALL
          KeySchema:
            - AttributeName: country
              KeyType: HASH
            - AttributeName: location
              KeyType: RANGE
        - IndexName: country-registration-index
          Projection:
            ProjectionType: ALL
          KeySchema:
            - AttributeName: country
              KeyType: HASH
            - AttributeName: registration
              KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

Outputs:
  HttpRequestApi:
    Description: "API Gateway endpoint URL for Prod stage for DynamoDB lambda functions"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  DynamoDBTableName:
    Value: {Ref: ExampleTableArn}
    Description: DynamoDB Table Name
